### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by oeway** [BachiLi/diffvg#4]
When running `single_gradient.py`, the entire process crashes with a `Segmentation fault (core dumped)` error.
```bash
~/diffvg/apps$ CUDA_VISIBLE_DEVICES=1 python single_gradient.py 
Segmentation fault (core dumped)
```

I tried to remove some part of the code and found the error was triggered by the following call to `render`:
```python
render = pydiffvg.RenderFunction.apply
img = render(256, # width
             256, # height
             2,   # num_samples_x
             2,   # num_samples_y
             0,   # seed
             None, # background_image
             *scene_args)
```
I am using Python 3.7.9 [GCC 7.3.0] :: Anaconda, on Mac, my torch version is 1.6.0

**Comment by fuyunfei** [comment]
Hi @oeway  did you find the solution ?  

The same thing happened to me too , the other scripts running well , just 
the single_gradient.py reports: 
Segmentation fault (core dumped)

**Comment by oeway** [comment]
no, I didn't find a solution.

**Comment by BachiLi** [comment]
Sorry, there must be a bug here. I need to check this. Give me a few days.

**Comment by fuyunfei** [comment]
@BachiLi  Hi, Bachili, I still can't figure it out, did you find any solution ?

**Comment by BachiLi** [comment]
@fuyunfei @oeway Should be fixed now. Let me know if there's any issue.

**Comment by BachiLi** [comment]
Closing as I'm pretty sure it's fixed. Feel free to reopen.
